"use client";

import React, { useState, useEffect, Suspense } from "react";
import Image from "next/image";
import { useSession } from "next-auth/react";
import { useRouter, useSearchParams } from "next/navigation";
import { 
  ShieldCheck, LockKeyOpen, Spinner, WarningCircle, 
  ArrowClockwise, IdentificationBadge, CrownSimple 
} from "@phosphor-icons/react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

function Verify2FAContent() {
  const { data: session, update } = useSession();
  const router = useRouter();
  const searchParams = useSearchParams();
  
  const userRole = (session?.user as any)?.role || "STAFF";
  const callbackUrl = searchParams.get("callbackUrl") || 
    (userRole === "ADMIN" ? "/quadrox-lorabiz-team/mds" : "/quadrox-lorabiz-team/staff");

  const [code, setCode] = useState("");
  const [loading, setLoading] = useState(false);
  const [resendLoading, setResendLoading] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");

  // Automatically dispatch verification OTP via SMTP if user utilizes Email 2FA
  useEffect(() => {
    const triggerEmailDispatch = async () => {
      if ((session?.user as any)?.twoFactorEnabled && !message) {
        try {
          await fetch("/api/auth/2fa/send-otp", { method: "POST" });
        } catch (err) {
          console.error("Silent background OTP dispatch failed", err);
        }
      }
    };
    if (session?.user) {
      triggerEmailDispatch();
    }
  }, [session]);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (code.length !== 6) {
      setError("Please enter your complete 6-digit verification passkey.");
      return;
    }

    setLoading(true);
    setError("");
    setMessage("");

    try {
      const res = await fetch("/api/auth/2fa/verify", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ code }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Cryptographic verification failed.");

      // Upgrade active session clearance state
      await update({ mfaVerified: true });
      router.push(callbackUrl);
      router.refresh();
    } catch (err: any) {
      setError(err.message || "Invalid passkey. Please check your app or email inbox.");
    } finally {
      setLoading(false);
    }
  };

  const handleResendOtp = async () => {
    setResendLoading(true);
    setError("");
    setMessage("");

    try {
      const res = await fetch("/api/auth/2fa/send-otp", { method: "POST" });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to dispatch email passkey.");
      setMessage("A fresh verification code has been dispatched to your corporate email.");
    } catch (err: any) {
      setError(err.message || "Could not dispatch code right now. Try again later.");
    } finally {
      setResendLoading(false);
    }
  };

  const isExecutive = userRole === "ADMIN";

  return (
    <div className={`min-h-screen w-full flex items-center justify-center bg-slate-950 text-slate-100 p-6 font-sans selection:text-black ${
      isExecutive ? "selection:bg-amber-500" : "selection:bg-teal-500"
    }`}>
      <div className="w-full max-w-md bg-slate-900 border border-slate-800 rounded-2xl p-6 sm:p-10 shadow-2xl relative overflow-hidden">
        
        {/* Ambient Glow */}
        <div className={`absolute -top-24 -left-24 w-48 h-48 rounded-full blur-[80px] pointer-events-none ${
          isExecutive ? "bg-amber-500/10" : "bg-teal-500/10"
        }`} />

        <div className="flex flex-col items-center text-center mb-8 relative z-10">
          <Image 
            src="/logo.png" 
            alt="LoraBiz Logo" 
            width={160} 
            height={50} 
            className="object-contain h-10 w-auto brightness-200 mb-6"
          />
          <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-full bg-slate-800/80 border text-xs font-semibold uppercase tracking-wider mb-3 ${
            isExecutive ? "border-amber-500/30 text-amber-400" : "border-teal-500/30 text-teal-400"
          }`}>
            {isExecutive ? <CrownSimple weight="bold" className="h-3.5 w-3.5" /> : <IdentificationBadge weight="bold" className="h-3.5 w-3.5" />}
            <span>{isExecutive ? "Executive 2FA Clearance" : "Staff Operations Clearance"}</span>
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-white">
            Identity Verification
          </h1>
          <p className="text-xs text-slate-400 mt-1.5 leading-relaxed">
            Please input the 6-digit security passkey generated by your authenticator app or dispatched to your corporate email.
          </p>
        </div>

        {error && (
          <div className="mb-6 p-4 bg-rose-500/10 border border-rose-500/20 rounded-xl flex items-center gap-2.5 text-rose-400 text-xs font-medium animate-in shake">
            <WarningCircle weight="fill" className="h-4.5 w-4.5 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        {message && (
          <div className="mb-6 p-4 bg-emerald-500/10 border border-emerald-500/20 rounded-xl flex items-center gap-2.5 text-emerald-400 text-xs font-medium animate-in fade-in">
            <ShieldCheck weight="fill" className="h-4.5 w-4.5 shrink-0" />
            <span>{message}</span>
          </div>
        )}

        <form onSubmit={handleVerify} className="space-y-6 relative z-10">
          <div className="space-y-2">
            <Input
              type="text"
              maxLength={6}
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
              placeholder="000000"
              autoFocus
              className={`h-14 text-center tracking-[0.55em] font-mono text-2xl bg-slate-950 border-slate-800 text-white focus-visible:ring-1 max-w-[240px] mx-auto block shadow-inner ${
                isExecutive ? "focus-visible:ring-amber-500 focus-visible:border-amber-500" : "focus-visible:ring-teal-500 focus-visible:border-teal-500"
              }`}
            />
          </div>

          <Button
            type="submit"
            disabled={loading || code.length !== 6}
            className={`w-full h-13 font-semibold text-black shadow-lg transition-all cursor-pointer flex items-center justify-center gap-2 ${
              isExecutive 
                ? "bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 shadow-amber-500/10" 
                : "bg-gradient-to-r from-teal-500 to-cyan-600 hover:from-teal-400 hover:to-cyan-500 shadow-teal-500/10"
            }`}
          >
            {loading ? (
              <Spinner className="animate-spin h-5 w-5 text-black" />
            ) : (
              <>Authorize Session <LockKeyOpen weight="bold" className="h-4.5 w-4.5" /></>
            )}
          </Button>

          <div className="pt-3 border-t border-slate-800/80 flex items-center justify-between text-xs text-slate-400">
            <span>Didn't receive a passkey?</span>
            <button
              type="button"
              onClick={handleResendOtp}
              disabled={resendLoading}
              className={`font-medium flex items-center gap-1.5 hover:underline focus:outline-none cursor-pointer ${
                isExecutive ? "text-amber-400" : "text-teal-400"
              }`}
            >
              {resendLoading ? <Spinner className="animate-spin h-3.5 w-3.5" /> : <ArrowClockwise className="h-3.5 w-3.5" />}
              <span>Resend Code</span>
            </button>
          </div>
        </form>

        <div className="mt-8 text-center relative z-10">
          <p className="text-[10px] tracking-widest text-slate-600 uppercase font-semibold">
            Quadrox Technologies Ltd &bull; Zero-Trust Gate
          </p>
        </div>

      </div>
    </div>
  );
}

export default function Verify2FAPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen w-full flex items-center justify-center bg-slate-950">
        <Spinner className="animate-spin h-8 w-8 text-teal-500" weight="bold" />
      </div>
    }>
      <Verify2FAContent />
    </Suspense>
  );
}
