import crypto from "crypto";
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function POST(req: Request) {
  try {
    // 1. Extract the raw body and the Paystack signature
    const body = await req.text();
    const signature = req.headers.get("x-paystack-signature");

    if (!signature) {
      return NextResponse.json({ message: "No signature found" }, { status: 400 });
    }

    // 2. Cryptographic Verification (Ensures it's actually Paystack)
    const secret = process.env.PAYSTACK_SECRET_KEY as string;
    const expectedSignature = crypto.createHmac("sha512", secret).update(body).digest("hex");

    if (signature !== expectedSignature) {
      return NextResponse.json({ message: "Invalid signature" }, { status: 400 });
    }

    const event = JSON.parse(body);

    // 3. Process the successful charge
    if (event.event === "charge.success") {
      const reference = event.data.reference;
      const amountPaid = Number(event.data.amount) / 100; // Convert Kobo to Naira
      const userEmail = event.data.customer.email;

      // We only care about Online checkout references generated by our system
      if (!reference.startsWith("ONL_")) {
        return NextResponse.json({ received: true });
      }

      const registrationId = reference.split("_")[1];

      // 4. ATOMIC TRANSACTION (Kills Race Conditions with the Frontend Verify API)
      await prisma.$transaction(async (tx: any) => {
        const user = await tx.user.findUnique({ 
          where: { email: userEmail }, 
          include: { wallet: true } 
        });
        
        if (!user || !user.wallet) return; // Silent fail, bad data

        // IDEMPOTENCY LOCK: If the frontend already verified this, STOP here.
        const existingTx = await tx.transaction.findUnique({ where: { reference } });
        if (existingTx && existingTx.status === "SUCCESS") {
          return; 
        }

        // --- MULTI-SERVICE DETECTION LOGIC ---
        let serviceType: "business" | "llc" | null = null;
        let regName = "Registration";

        // First, check if it's a Business Name
        const bizReg = await tx.businessRegistration.findUnique({ where: { id: registrationId } });
        if (bizReg) {
          if (bizReg.status !== "UNSUBMITTED") return; // Already paid
          serviceType = "business";
          regName = bizReg.proposedName;
        } else {
          // If not a Business Name, check if it's an LLC
          const llcReg = await tx.llcRegistration.findUnique({ where: { id: registrationId } });
          if (llcReg) {
            if (llcReg.status !== "UNSUBMITTED") return; // Already paid
            serviceType = "llc";
            regName = llcReg.proposedName || "LLC Application";
          }
        }

        // If no matching unsubmitted registration is found in ANY table, exit safely.
        if (!serviceType) return; 

        // STEP A: FUND THE WALLET
        const currentBalance = Number(user.wallet.balance);
        const newBalanceAfterFunding = currentBalance + amountPaid;

        await tx.transaction.create({
          data: {
            walletId: user.wallet.id,
            amount: amountPaid,
            balanceBefore: currentBalance,
            balanceAfter: newBalanceAfterFunding,
            type: "CREDIT",
            status: "SUCCESS",
            reference: reference, 
            description: "Paystack Online Funding (Webhook)"
          }
        });

        // STEP B: EXACT SIMULTANEOUS DEBIT
        const newBalanceAfterPayment = newBalanceAfterFunding - amountPaid;

        await tx.transaction.create({
          data: {
            walletId: user.wallet.id,
            amount: amountPaid,
            balanceBefore: newBalanceAfterFunding,
            balanceAfter: newBalanceAfterPayment,
            type: "DEBIT",
            status: "SUCCESS",
            reference: `SRV_PAY_${registrationId}_${Date.now()}`,
            description: `Payment for Registration (${regName})`
          }
        });

        // STEP C: UPDATE BALANCE & REGISTRATION
        await tx.wallet.update({
          where: { id: user.wallet.id },
          data: { balance: newBalanceAfterPayment } 
        });

        // Update the specific database table based on what they registered
        if (serviceType === "business") {
          await tx.businessRegistration.update({
            where: { id: registrationId },
            data: { status: "PENDING" } 
          });
        } else if (serviceType === "llc") {
          await tx.llcRegistration.update({
            where: { id: registrationId },
            data: { status: "PENDING" } 
          });
        }
      });
    }

    // Always return 200 OK to Paystack so they stop retrying
    return NextResponse.json({ received: true });
  } catch (error) {
    console.error("Webhook Error:", error);
    return NextResponse.json({ message: "Webhook error" }, { status: 500 });
  }
}
